@localUrl = http://localhost:3001/api/notes
# @baseUrl = https://fullstackopen-pz0g.onrender.com/api/notes
@id = 68f524d48e3b10f19fb4a3cb


### Get all notes
GET {{localUrl}}


### Get a note by id
GET {{localUrl}}/{{id}}


### Create new note
POST {{localUrl}}
Content-Type: application/json

{
  "content": "The existing code and tests need to be changed when user is added to the system",
  "important": true,
  "userId": "68f5313036cb697134782daa"
}


### Delete note
DELETE {{localUrl}}/{{id}}


### Update note
PUT {{localUrl}}/{{id}}
Content-Type: application/json

{
  "content": "HTML is REALLY easy",
  "important": false
}