@localUrl = http://localhost:3001/api/notes
# @baseUrl = https://fullstackopen-pz0g.onrender.com/api/notes
@id = 68f524d48e3b10f19fb4a3cb


### Get all notes
GET {{localUrl}}


### Get a note by id
GET {{localUrl}}/{{id}}


### Create new note
POST {{localUrl}}
Content-Type: application/json

{
  "content": "User id of the note creator is at the start sent along the request",
  "important": true,
  "userId": "68f50d8802c3cb282e2a17b0"
}


### Delete note
DELETE {{localUrl}}/{{id}}


### Update note
PUT {{localUrl}}/{{id}}
Content-Type: application/json

{
  "content": "HTML is REALLY easy",
  "important": false
}