@baseUrl = http://localhost:3000/api

POST {{baseUrl}}/diaries
Content-Type: application/json

{
  "date": "2024-01-01",
  "weather": "sunny",
  "visibility": "awesome",
  "comment": "good stuff but scary"
}