@localUrl = http://localhost:3001
@baseUrl = https://phonebook-kj3t.onrender.com
@id = 68ecf7efda1dc92887efa82b


### Get all persons
GET {{baseUrl}}/api/persons


### Get a person info
GET {{baseUrl}}/api/persons/{{id}}


### Get phonebook info
GET {{baseUrl}}/info


### Add person
POST {{localUrl}}/api/persons
Content-Type: application/json

{
  "name": "Bastien",
  "number": "00000000000000"
}


### Delete person
DELETE {{baseUrl}}/api/persons/{{id}}


### Update person
PUT {{localUrl}}/api/persons/{{id}}
Content-Type: application/json

{
  "name": "Anngrda",
  "number": "55"
}