@localUrl = http://localhost:3001/api/notes
@baseUrl = https://fullstackopen-pz0g.onrender.com/api/notes
@id = 68ecb897e8ab001681da0b6e


### Get all notes
GET {{baseUrl}}


### Get a note by id
GET {{baseUrl}}/{{id}}


### Create new note
POST {{localUrl}}
Content-Type: application/json

{
  "content": "",
  "important": true
}


### Delete note
DELETE {{baseUrl}}/{{id}}


### Update note
PUT {{localUrl}}/{{id}}
Content-Type: application/json

{
  "content": "HTML is REALLY easy",
  "important": false
}