@baseUrl = http://localhost:3001/api/notes
# @baseUrl = https://fullstackopen-pz0g.onrender.com/api/notes
@id = 4


### Get all notes
GET {{baseUrl}}


### Get a note by id
GET {{baseUrl}}/{{id}}


### Create new note
POST {{baseUrl}}
Content-Type: application/json

{
  "content": "Ensure evrything still works",
  "important": true
}


### Delete note
DELETE {{baseUrl}}/{{id}}