@localUrl = http://localhost:3001/api/notes
# @baseUrl = https://fullstackopen-pz0g.onrender.com/api/notes
@id =
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OGY1MzEzMDM2Y2I2OTcxMzQ3ODJkYWEiLCJpYXQiOjE3NjA5MDY2NDV9.Sb1j6l8FxWdon_vD2uGa-HI8e1grSrQcgxH71vtQyVs


### Get all notes
GET {{localUrl}}


### Get a note by id
GET {{localUrl}}/{{id}}


### Create new note
POST {{localUrl}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "content": "Single page apps use token based auth",
  "important": false
}


### Delete note
DELETE {{localUrl}}/{{id}}


### Update note
PUT {{localUrl}}/{{id}}
Content-Type: application/json

{
  "content": "HTML is REALLY easy",
  "important": false
}