@localUrl = http://localhost:3003/api/blogs
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OGY1NmNjNTFiM2QyMmIwZWJhY2JhYzciLCJpYXQiOjE3NjA5NTM5ODksImV4cCI6MTc2MDk1NzU4OX0.jjh5WpA6LD2iv1i0tYXfcvBL6aqRz6k-J4gPChseBRE
@blogId = 68f5768a7cf01cc0432d7917


### Get all blogs
GET {{localUrl}}


### Post new blog
POST {{localUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Auth blog",
  "author": "New one",
  "url": "https://example2.com",
  "likes": 1045
}


### Delete blog
DELETE {{localUrl}}/{{blogId}}
Authorization: Bearer {{token}}