@localUrl = http://localhost:3003/api/blogs


### Get all blogs
GET {{localUrl}}


### Post new blog
POST {{localUrl}}
Content-Type: application/json

{
  "title": "My First Blog",
  "author": "John Doe",
  "url": "https://example.com",
  "likes": 10
}